name: day35

on: push

env:
  NAME: Siddu
  CITY: Hyderabad

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v6

     - run: echo "Hello $NAME"

     - run: echo "WELCOME TO $CITY"
